# Generated by Django 2.1.dev20180407004606 on 2018-04-15 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='logo',
            field=models.ImageField(default='static/logo_post.jpg', upload_to='static'),
        ),
    ]
