# Generated by Django 2.0.4 on 2018-04-15 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratingorganization',
            name='logo',
            field=models.ImageField(default='static/logo_post.jpg', upload_to='static'),
        ),
        migrations.AddField(
            model_name='educationalproject',
            name='logo',
            field=models.ImageField(default='static/logo_post.jpg', upload_to='static'),
        ),
        migrations.AddField(
            model_name='industrialproject',
            name='logo',
            field=models.ImageField(default='static/logo_post.jpg', upload_to='static'),
        ),
    ]
