# Generated by Django 2.0.4 on 2018-04-15 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180415_0545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collaboratingorganization',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='educationalproject',
            old_name='description',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='industrialproject',
            old_name='description',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='collaboratingorganization',
            name='type',
        ),
        migrations.RemoveField(
            model_name='educationalproject',
            name='supporters',
        ),
        migrations.RemoveField(
            model_name='industrialproject',
            name='employer',
        ),
        migrations.RemoveField(
            model_name='industrialproject',
            name='supporters',
        ),
        migrations.AlterField(
            model_name='educationalproject',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
