# Generated by Django 2.0.4 on 2018-04-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180415_0548'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaboratingorganization',
            name='status',
            field=models.TextField(default='', max_length=50),
        ),
    ]
