# Generated by Django 2.0.4 on 2018-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_collaboratingorganization_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('text', models.TextField(max_length=500)),
                ('status', models.TextField(default='', max_length=50)),
            ],
        ),
    ]
