# Generated by Django 2.0.5 on 2018-05-23 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collaboratingorganization',
            name='logo',
            field=models.ImageField(default='logo_post.jpg', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='educationalproject',
            name='logo',
            field=models.ImageField(default='logo_post.jpg', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='industrialproject',
            name='logo',
            field=models.ImageField(default='logo_post.jpg', upload_to='projects'),
        ),
        migrations.AlterField(
            model_name='news',
            name='logo',
            field=models.ImageField(default='logo_post.jpg', upload_to='news'),
        ),
    ]
