# Generated by Django 2.0.5 on 2018-05-24 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180523_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='supporters',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
